# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_password_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_change_password_dlg(object):
    def setupUi(self, change_password_dlg):
        change_password_dlg.setObjectName("change_password_dlg")
        change_password_dlg.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(change_password_dlg)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.l_old_password = QtWidgets.QLabel(change_password_dlg)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.l_old_password.setFont(font)
        self.l_old_password.setObjectName("l_old_password")
        self.verticalLayout.addWidget(self.l_old_password)
        self.le_old_password = QtWidgets.QLineEdit(change_password_dlg)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.le_old_password.setFont(font)
        self.le_old_password.setText("")
        self.le_old_password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.le_old_password.setObjectName("le_old_password")
        self.verticalLayout.addWidget(self.le_old_password)
        self.l_new_password = QtWidgets.QLabel(change_password_dlg)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.l_new_password.setFont(font)
        self.l_new_password.setObjectName("l_new_password")
        self.verticalLayout.addWidget(self.l_new_password)
        self.le_new_password = QtWidgets.QLineEdit(change_password_dlg)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.le_new_password.setFont(font)
        self.le_new_password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.le_new_password.setObjectName("le_new_password")
        self.verticalLayout.addWidget(self.le_new_password)
        self.l_new_password_again = QtWidgets.QLabel(change_password_dlg)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.l_new_password_again.setFont(font)
        self.l_new_password_again.setObjectName("l_new_password_again")
        self.verticalLayout.addWidget(self.l_new_password_again)
        self.le_new_password_again = QtWidgets.QLineEdit(change_password_dlg)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.le_new_password_again.setFont(font)
        self.le_new_password_again.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.le_new_password_again.setObjectName("le_new_password_again")
        self.verticalLayout.addWidget(self.le_new_password_again)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(change_password_dlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(change_password_dlg)
        self.buttonBox.accepted.connect(change_password_dlg.accept)
        self.buttonBox.rejected.connect(change_password_dlg.reject)
        QtCore.QMetaObject.connectSlotsByName(change_password_dlg)

    def retranslateUi(self, change_password_dlg):
        _translate = QtCore.QCoreApplication.translate
        change_password_dlg.setWindowTitle(_translate("change_password_dlg", "修改密码"))
        self.l_old_password.setText(_translate("change_password_dlg", "请输入您的旧密码"))
        self.l_new_password.setText(_translate("change_password_dlg", "请输入您的新密码"))
        self.l_new_password_again.setText(_translate("change_password_dlg", "请重新输入您的新密码"))
