# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_house_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_select_house_dlg(object):
    def setupUi(self, select_house_dlg):
        select_house_dlg.setObjectName("select_house_dlg")
        select_house_dlg.resize(555, 376)
        self.gridLayout = QtWidgets.QGridLayout(select_house_dlg)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.l_select_house = QtWidgets.QLabel(select_house_dlg)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.l_select_house.setFont(font)
        self.l_select_house.setAlignment(QtCore.Qt.AlignCenter)
        self.l_select_house.setObjectName("l_select_house")
        self.verticalLayout.addWidget(self.l_select_house)
        self.label_4 = QtWidgets.QLabel(select_house_dlg)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.tbl_select_house = QtWidgets.QTableWidget(select_house_dlg)
        self.tbl_select_house.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_select_house.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_select_house.setRowCount(10000)
        self.tbl_select_house.setObjectName("tbl_select_house")
        self.tbl_select_house.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_select_house.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_select_house.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_select_house.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_select_house.setHorizontalHeaderItem(3, item)
        self.tbl_select_house.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tbl_select_house)
        self.l_time = QtWidgets.QLabel(select_house_dlg)
        self.l_time.setObjectName("l_time")
        self.verticalLayout.addWidget(self.l_time)
        self.label_5 = QtWidgets.QLabel(select_house_dlg)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.buttonBox = QtWidgets.QDialogButtonBox(select_house_dlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(select_house_dlg)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(select_house_dlg)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(select_house_dlg)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 1, 1, 1)

        self.retranslateUi(select_house_dlg)
        self.buttonBox.accepted.connect(select_house_dlg.accept)
        self.buttonBox.rejected.connect(select_house_dlg.reject)
        QtCore.QMetaObject.connectSlotsByName(select_house_dlg)

    def retranslateUi(self, select_house_dlg):
        _translate = QtCore.QCoreApplication.translate
        select_house_dlg.setWindowTitle(_translate("select_house_dlg", "选择房屋"))
        self.l_select_house.setText(_translate("select_house_dlg", "请选择您要交易的房屋"))
        item = self.tbl_select_house.horizontalHeaderItem(0)
        item.setText(_translate("select_house_dlg", "地址"))
        item = self.tbl_select_house.horizontalHeaderItem(1)
        item.setText(_translate("select_house_dlg", "面积"))
        item = self.tbl_select_house.horizontalHeaderItem(2)
        item.setText(_translate("select_house_dlg", "是否精装"))
        item = self.tbl_select_house.horizontalHeaderItem(3)
        item.setText(_translate("select_house_dlg", "价值"))
        self.l_time.setText(_translate("select_house_dlg", "查询时间：0.0s"))
